### ISSUE TITLE
Possible to add Style prop?

### ISSUE THREAD

**Issue by seanlindo** [jsdir/react-ladda#43]
This would be helpful if you work primarily with inline styles and, for example, would like to make a button 100% width. I can make a PR for this!

**Comment by jsdir** [comment]
You should be able to use `style` prop on `LaddaButton` since we are [passing props](https://github.com/jsdir/react-ladda/blob/1f558eb07e026533820ff9b0d8afe91008c4ec77/src/LaddaButton.jsx#L90) on the `LaddaButton` directly to the internal button anyway. However, this feature isn't documented anywhere. We can discuss documentation for this on #42.
